# Generated by Django 2.2.28 on 2023-06-28 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '__first__'),
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseuser',
            name='target_server',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='orchestration.Server', verbose_name='Target Server'),
        ),
    ]
