# Generated by Django 2.2.28 on 2023-06-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '__first__'),
        ('databases', '0002_databaseuser_target_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseuser',
            name='permision',
            field=models.CharField(choices=[('all', 'all'), ('ro', 'read only')], default='all', max_length=20, verbose_name='Permisson'),
        ),
        migrations.AlterField(
            model_name='databaseuser',
            name='target_server',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='orchestration.Server', verbose_name='Server'),
        ),
        migrations.AlterUniqueTogether(
            name='databaseuser',
            unique_together={('username', 'type', 'target_server')},
        ),
    ]
