# Generated by Django 2.2.28 on 2023-06-29 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '__first__'),
        ('databases', '0003_auto_20230629_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='target_server',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='orchestration.Server', verbose_name='Server'),
        ),
    ]
