# Generated by Django 2.2.28 on 2023-07-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '__first__'),
        ('databases', '0004_database_target_server'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='database',
            unique_together={('name', 'type', 'target_server')},
        ),
    ]
