# Generated by Django 2.2.28 on 2023-07-05 10:37

from django.db import migrations, models
import orchestra.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0005_auto_20230705_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseuser',
            name='username',
            field=models.CharField(max_length=32, validators=[orchestra.core.validators.validate_name], verbose_name='username'),
        ),
    ]
