# Generated by Django 2.2.28 on 2023-07-24 16:13

from django.db import migrations, models
import orchestra.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('systemusers', '0002_webappusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webappusers',
            options={'verbose_name': 'WebAppUser', 'verbose_name_plural': 'WebappUsers'},
        ),
        migrations.AlterField(
            model_name='webappusers',
            name='home',
            field=models.CharField(blank=True, help_text='name dir webapp /home/&lt;main&gt;/webapps/&lt;DirName&gt;', max_length=256, validators=[orchestra.core.validators.validate_string_dir], verbose_name='WebappDir'),
        ),
    ]
