# Generated by Django 2.2.28 on 2023-08-17 09:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orchestration', '__first__'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='website',
            unique_together={('name', 'account', 'target_server')},
        ),
    ]
